# Write your MySQL query statement below
SELECT P.PRODUCT_NAME,SUM(O.UNIT) AS UNIT FROM PRODUCTS P,ORDERS O WHERE P.PRODUCT_ID = O.PRODUCT_ID AND O.ORDER_DATE BETWEEN '2020-02-01' AND '2020-02-29' GROUP BY O.PRODUCT_ID HAVING UNIT >= 100 ORDER BY O.PRODUCT_ID;
